name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.9  # Set Node.js version to 22.9
          cache: 'yarn'

      # Install dependencies using Yarn
      - run: yarn install --check-files --force

      # Set Nx SHAs for the workspace
      - uses: nrwl/nx-set-shas@v4

      # Run Nx tasks with lint, test, and build
      - run: npx nx affected -t lint test build
